backend:
  name: git-gateway
  repo: MakersAsylumIndia/makersasylum.com

media_folder: "_uploads"
public_folder: "/uploads"

collections:
  - name: "press"
    label: "Press Items"
    singular_label: "Press Item"
    folder: "_press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publication", name: "publication", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Publication Date", name: "date", widget: "date"}
  - name: "projects"
    label: "Projects"
    singular_label: "Project"
    folder: "_projects"
    extension: "markdown"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featured image", widget: "image"}
      - label: "Pictures"
        name: "pictures"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Description", name: "alt", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "membership-plans"
    label: "Membership Plans"
    singular_label: "Membership Plan"
    folder: "_membership-plans"
    extension: "markdown"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "number"}
      - {label: "Validity", name: "validity", widget: "string"}
      - {label: "Has tool access?", name: "has tool access", widget: "boolean"}
      - {label: "Has community events?", name: "has community events", widget: "boolean"}
      - {label: "Locker access duration", name: "locker access", widget: "string"}
      - {label: "Benefits", name: "benefits", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Payment link", name: "link", widget: "string"}
