backend:
  name: git-gateway
  repo: MakersAsylumIndia/makersasylum.com

media_folder: "_uploads"
public_folder: "/uploads"

collections:
  - name: "press"
    label: "Press Items"
    singular_label: "Press Item"
    folder: "_press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publication", name: "publication", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Publication Date", name: "date", widget: "date", format: "DD-MM-YYYY"}
  - name: "projects"
    label: "Projects"
    singular_label: "Project"
    folder: "_projects"
    extension: "markdown"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featured image", widget: "image"}
      - label: "Pictures"
        name: "pictures"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Image Description", name: "alt", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
